### ISSUE TITLE
Ping notification doesn't work in dev container (in docker)

### ISSUE THREAD

**Issue by Mikaka27** [2514millerj/vscode-meerkatio#1]
Hi,

When using your extension with ping notification, the sound is not playing after some command finishes execution.
This happens when using dev container (docker). This is what I get in dev tools:
![image](https://github.com/2514millerj/vscode-meerkatio/assets/9214100/516ef086-90d7-4c99-95a9-3cd5139412ce)

I'm not sure if this is something that can be fixed from extension side, or maybe dev container would need to have access to pulseaudio/pipewire socket?

**Comment by 2514millerj** [comment]
Hello, thank you for diving into this bug! Would you be able to provide the proper steps to reproduce this issue? What Docker dev setup are you working with?

**Comment by Mikaka27** [comment]
Steps to reproduce would be:
1. Meet requirements listed here: https://code.visualstudio.com/docs/devcontainers/containers
2. Install this extension pack: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
3. `git clone -b maint git@github.com:erlang/otp`
4. Open otp directory in vscode
5. You should be prompted by vscode whether you want to reopen in dev container
6. Click yes
7. Wait until vscode loads in dev container (building the container takes a few minutes)
8. Open terminal in vscode
9. Run `export ERL_TOP=$(pwd)`
10. Execute `./otp_build configure && make`
11. After this finishes you expect to hear the ping notification
12. I get the error in vscode dev tools instead

**Comment by 2514millerj** [comment]
Thank you for the detailed steps, I was able to reproduce this issue. Unfortunately there is nothing on the extension end that solves this problem. VS Code allows extensions to either run locally in the UI or from wherever the workspace is hosted. MeerkatIO cannot run from the UI because it needs to monitor processes running in the workspace including terminal commands and Jupyter kernels, which it would not have access to as a UI extension.

My recommended solution is to either configure a setup similar to the below steps or to use the other notification methods available through the extension such as Email, Slack, or SMS.

1. Install Pulseaudio on your local machine
2. Run `pulseaudio --load="module-native-protocol-tcp" --exit-idle-time=-1 --daemon` to start a pulseaudio daemon on your local machine
3. Add Docker runtime arguments to devcontainer.json
```
"runArgs": [
    "-e", "PULSE_SERVER=host.docker.internal"
]
```
4. Add a postCreateCommand to devcontainer.json to install the pulseaudio tool inside of the Docker container
```
"postCreateCommand": "apt-get install -y pulseaudio"
```

**Comment by Mikaka27** [comment]
Ok thanks for checking, I also thought that it is not fixable on extension side :(
